from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/verify/', views.request_verification, name='request_verification'),
    path('profile/<str:username>/', views.profile_detail, name='profile_detail'),
    path('skills/', views.manage_skills, name='manage_skills'),
    path('skills/<int:userskill_id>/delete/', views.delete_user_skill, name='delete_user_skill'),
    path('explore/', views.explore_users, name='explore_users'),
    path('request/<str:username>/', views.send_swap_request, name='send_swap_request'),
    path('requests/<int:request_id>/accept/', views.accept_swap_request, name='accept_swap_request'),
    path('requests/<int:request_id>/reject/', views.reject_swap_request, name='reject_swap_request'),
    path('requests/<int:request_id>/cancel/', views.cancel_swap_request, name='cancel_swap_request'),
    path('sessions/', views.sessions_list, name='sessions_list'),
    path('sessions/<int:session_id>/', views.session_detail, name='session_detail'),
    path('sessions/<int:session_id>/message/', views.send_session_message, name='send_session_message'),
    path('sessions/<int:session_id>/complete/', views.complete_session, name='complete_session'),
    path('sessions/<int:session_id>/review/', views.review_session, name='review_session'),
    path('sessions/<int:session_id>/proof/', views.add_proof, name='add_proof'),
    path('chat/', views.chat_inbox, name='chat_inbox'),
    path('notifications/', views.notifications_list, name='notifications_list'),
    path('favorites/', views.favorites_list, name='favorites_list'),
    path('favorites/<str:username>/toggle/', views.toggle_favorite, name='toggle_favorite'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('challenges/', views.challenges_list, name='challenges_list'),
    path('peer-challenges/', views.peer_challenges_list, name='peer_challenges_list'),
    path('peer-challenges/create/<str:username>/', views.create_peer_challenge, name='create_peer_challenge'),
    path('peer-challenges/<int:challenge_id>/', views.peer_challenge_detail, name='peer_challenge_detail'),
    path('peer-challenges/<int:challenge_id>/accept/', views.accept_peer_challenge, name='accept_peer_challenge'),
    path('peer-challenges/<int:challenge_id>/reject/', views.reject_peer_challenge, name='reject_peer_challenge'),
    path('peer-challenges/<int:challenge_id>/cancel/', views.cancel_peer_challenge, name='cancel_peer_challenge'),
    path('peer-challenges/<int:challenge_id>/proof/', views.submit_peer_challenge_proof, name='submit_peer_challenge_proof'),
    path('challenges/leaderboard/', views.challenge_leaderboard, name='challenge_leaderboard'),
    path('challenges/<int:challenge_id>/', views.challenge_detail, name='challenge_detail'),
    path('report/<str:username>/', views.report_user, name='report_user'),
    path('moderation/', views.moderation_center, name='moderation_center'),
    path('moderation/reports/<int:report_id>/resolve/', views.resolve_report, name='resolve_report'),
    path('moderation/verification/<int:verification_id>/approve/', views.approve_verification, name='approve_verification'),
    path('moderation/verification/<int:verification_id>/reject/', views.reject_verification, name='reject_verification'),
]
